# Not read by any node, but used by launch file to create a static TF for the camera
# X Y Z R P Y parent_frame child_frame
# child_frame must match that defined in aruco_node_params.yaml
camera_tf : ["1","1","1","1.57","0","0","world","usb_camera_link"]